### ISSUE TITLE
Configure two command buses

### ISSUE THREAD

**Issue by carnau** [thephpleague/tactician-bundle#105]
I've been following the README but I can get this working. I want to have two command buses that doesn't share the same commands, but seems that adding the bus tag in services.yml is not enough.

Do I have to add any other configuration? Adding the default handler as console works, but I guess that then it will not find the commands of the default bus.

```
tactician:
    commandbus:
        default:
            middleware:
                - tactician.middleware.custom_middleware
                - tactician.middleware.another_custom_middleware
                - tactician.middleware.command_handler
        console:
            middleware:
                - tactician.middleware.command_handler
```

```
App\Application\Handler\ExampleHandler:
        class: App\Application\Handler\ExampleHandler
        autowire: false
        arguments:
            - '@App\Infrastructure\Http\Example\Client'
        tags:
            - { name: tactician.handler, command: App\Application\Command\ExampleCommand, bus: console }
```

`Missing handler for command App\Application\Command\ExampleCommand`
