### ISSUE TITLE
Handlers are not picked up by Tactician

### ISSUE THREAD

**Issue by sarjon** [thephpleague/tactician-bundle#114]
Hey guys,

so I've faced weird problem. When I define handlers in `config/services.yaml` it all works well, but once I move my handlers into separate file, lets say `config/services/command_handlers.yaml` and import that file into `config/service.yaml`, those handlers defined in separate file are not picked up by Tactician. :confused: 

Any ideas of what I'm missing? Thanks in advance! :slightly_smiling_face: 

Btw, I'm on Symfony 4.3 and PHP 7.3.

**Comment by sarjon** [comment]
Haha, seems I've figured it out. The problem was with how services get loaded into container. This is simplified version of how my `services.yaml` looks like:

```yaml
imports:
  #  This will import tagged command handlers from external file
  - { resource: services/command_handlers.yaml } 

services:
 # This will override previously imported command handlers thus removing tags
  App\:
    resource: '../src/*'
```

So what I did is excluded my command handlers directory from being loaded again:

```yaml
imports:
  - { resource: services/command_handlers.yaml } 

services:
  App\:
    resource: '../src/*'
    exclude:
        - './src/CommandHandler/*' # Exclude loading command handlers once again
```

Hopefully this could help others with the same issue. :stuck_out_tongue:
