### ISSUE TITLE
RFC Allow specifying which command bus to register a handler on

### ISSUE THREAD

**Issue by benglass** [thephpleague/tactician-bundle#19]
This is an idea for a feature, if it would be welcome I would be willing to work on a PR

The idea is to allow tagging a handler and specifying which command bus you want to add it to.

This would allow you to have a command bus for sending notifications, for example, in addition to the primary command bus and you could register two handlers on a command such as RegisterUserCommand on differenet buses.

For example, the default bus might handle the actual user registration (generating salt, updating the db, etc.) while a notification bus might handle sending the email.

I know this can be achieved with custom middleware in various ways but it seems like it would be convenient and flexible to let consumers have multiple buses with different responsibilities (logging, notification, etc.) and register handles on specific buses for the same command.

This should be rather simple to implement in the compiler pass and if its of interest I can work on a PR.

**Comment by boekkooi** [comment]
Hi @benglass,

I'm sorry to say that I'm probably missing your point.

But are you proposing a `tactician.middleware.command_handler` and `tactician.handler.locator.symfony` per command bus? 

Where in that case the command handler can be tagged using:
```
foo.user.register_user_handler:
    class: Foo\User\RegisterUserHandler
    tags:
        - { name: tactician.handler, command: Foo\User\RegisterUserCommand, bus: 'main' }

foo.user.register_user_handler_email:
    class: Foo\User\RegisterUserEmailHandler
    tags:
        - { name: tactician.handler, command: Foo\User\RegisterUserCommand, bus: 'bus2' }
```

If this is what you propose I'm :-1: on this one because it just feels like bad architecture (and it starts to look like events).
