### ISSUE TITLE
Support Changing Method Inflectors

### ISSUE THREAD

**Issue by rdohms** [thephpleague/tactician-bundle#3]
We should be able to support changing the method Inflector to use.

```yml
tactician:
    default: 
        method_inflector: "tactician.handler.inflector.handle"
```
