### ISSUE TITLE
Multiple command buses

### ISSUE THREAD

**Issue by notFloran** [thephpleague/tactician-bundle#63]
Hi !

First of all thank you for the lib and bundle !

I want to set multiple command buses like explained in the README with:

```
tactician:
    commandbus:
        default:
            middleware:
                - tactician.middleware.command_handler
        queued:
            middleware:
                - tactician.middleware.queued_command_handler
``` 

But I got the following error:

``` 
  [League\Tactician\Bundle\DependencyInjection\Compiler\UnknownMiddlewareException]
  Unknown middleware with service id "tactician.middleware.queued_command_handler".
```

What do I miss?
