### ISSUE TITLE
[Support] Missing handler for many buses

### ISSUE THREAD

**Issue by TrogWarZ** [thephpleague/tactician-bundle#81]
Hello! This is support issue, so i just need your help and answer what i'm doing wrong.

My goal is to use default configuration for all my handlers, but exclude doctrine middleware for some of them.
In this example, `foobar` needs to run without doctrine at all, but `sup` needs default config.
Symfony version is `^3.3` and this bundle `^1.0`. Caches are cleared after any changes in configuration.

## Configuration

`./app/config/bundles/commandbus.yml`:

```yaml
tactician:
    commandbus:
        no_doctrine:
            middleware:
                - tactician.middleware.locking
                - tactician.middleware.validator
                - tactician.middleware.command_handler
        default:
            middleware:
                - tactician.middleware.locking
                - tactician.middleware.doctrine
                - tactician.middleware.validator
                - tactician.middleware.command_handler
```

`./app/config/services/commandbus.yml`:

```yaml
services:
    acme.foobar:
        class     : AppBundle\CommandBus\FoobarCommandHandler
        arguments : []
        tags      : [{ bus: no_doctrine, name: tactician.handler, command: AppBundle\CommandBus\FoobarCommand }]
```

Result of  debugging configuration: `./bin/console debug:tactician`
```
Tactician routing
=================

Bus: no_doctrine
----------------

 ------------------------------------ -----------------
  Command                              Handler Service
 ------------------------------------ -----------------
  AppBundle\CommandBus\FoobarCommand   acme.foobar
 ------------------------------------ -----------------

Bus: default
------------

 --------------------------------- -----------------
  Command                           Handler Service
 --------------------------------- -----------------
  AppBundle\CommandBus\SupCommand   acme.sup
 --------------------------------- -----------------
```
## Code

This works good (for all commands that using default configuration):
```php
$bus = $this->container->get('tactician.commandbus');
$bus->handle(new \AppBundle\CommandBus\SupCommand());
```

But any of this ways doesn't working and throw exception "Missing handler for command":
```php
$bus = $this->container->get('tactician.commandbus');
$bus->handle(new \AppBundle\CommandBus\FoobarCommand());

$bus = $this->container->get('tactician.commandbus.no_doctrine');
$bus->handle(new \AppBundle\CommandBus\FoobarCommand());
```
