### ISSUE TITLE
Typehint mapping and setter injection

### ISSUE THREAD

**Issue by jverdeyen** [thephpleague/tactician-bundle#90]
I have a question/issue about/with Typehint mapping and setter injection.

I implement an interface on all of my handler classes:

```
    _instanceof:
        AppBundle\Service\HandlerInterface:
            tags:
                - { name: tactician.handler, typehints: false }
            autowire: true
            public: true
```

All goes fine by this.

But one handler requires a setter injection, for example.

```
    /**
     * @param EntityManagerInterface $em
     *
     * @required
     */
    public function setEm(EntityManagerInterface $em): void
    {
        $this->em = $em;
    }
```

The problem here is that the `findCommandsForService` in `TypeHintMapping` will find this function and tries to map it.
This will trigger the following error:

```
Can not route Doctrine\ORM\EntityManagerInterface to AppBundle\Service\Membership\MembershipRegistrationHandler, class Doctrine\ORM\EntityManagerInterface does not exist!
```

Because of

```
if (!class_exists($commandClassName)) {
    throw new InvalidArgumentException("Can not route $commandClassName to $serviceId, class $commandClassName does not exist!");
}
```

I could create a custom mapping, which only checks for a `handle` function instead of all other function in my class. But is this the expected behaviour? Or should we filter out functions with interface typehinting?

Thanks!
